### ISSUE TITLE
Unable to install seeds

### ISSUE THREAD

**Issue by vincedev** [devxoul/CocoaSeeds#49]
I'm not able to install seeds, when I run `seed install`, I get the following error :

```
% seed install                                                                                                                                                   
Anaylizing dependencies
/Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.6.0/lib/cocoaseeds/core.rb:315:in `eval': undefined local variable or method `“master”' for #<Seeds::Core:0x007fa2ebc20f98> (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.6.0/lib/cocoaseeds/core.rb:315:in `eval'
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.6.0/lib/cocoaseeds/core.rb:315:in `execute_seedfile'
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.6.0/lib/cocoaseeds/core.rb:104:in `install'
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.6.0/lib/cocoaseeds/command.rb:11:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.6.0/bin/seed:5:in `<top (required)>'
    from /usr/local/bin/seed:23:in `load'
    from /usr/local/bin/seed:23:in `<main>'
 %
```

**Comment by devxoul** [comment]
Hi @vincedev,
How did you setup your Seedfile?

I think you should enclose `master` with quotes.

For example:

**Wrong**

<pre>
github "SwiftyJSON/SwiftyJSON", <b>master</b>, :files => "Source/*.{swift,h}"
</pre>

**Correct**

<pre>
github "SwiftyJSON/SwiftyJSON", <b>"master"</b>, :files => "Source/*.{swift,h}"
</pre>

**Comment by vincedev** [comment]
Hoo, it seems there is a mistake with quotes..

```
xcodeproj "Test/Test.xcodeproj"
swift_seedname_prefix!

github "socketio/socket.io-client-swift", “master”, :files => "Source/*.swift" # Or latest version

target :ios do
    github "kasketis/netfox", "master", :files => "netfox/*.swift"
    github "filipstefansson/AutocompleteField", "master", :files => "AutocompleteField/*.swift"
end

target :osx do
  github "timothyarmes/TAAdaptiveSpaceItem", "master", :files => "TAAdaptiveSpaceItem/*.{h,m}"
end
```

Here with **“master”**.
Back with _normal_ quotes, it run as expected.

**Comment by devxoul** [comment]
Oh, what a 'smart' quote. :smile:
